CREATE TABLE TBL_USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NM_USUARIO VARCHAR(100) NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL,
    DS_CPF VARCHAR(11) NOT NULL,
    DS_SENHA VARCHAR(255) NOT NULL
);
