CREATE TABLE TBL_RECEITA (
    ID_RECEITA INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    VL_RECEITA DECIMAL(10, 2) NOT NULL,
    DT_RECEITA DATETIME NOT NULL,
    TX_DESCRICAO VARCHAR(200),
    FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO)
);
