CREATE TABLE TBL_HISTORICO_RECEITAS (
    ID_HISTORICO_RECEITAS INT IDENTITY(1,1) PRIMARY KEY,
    ID_RECEITA INT NOT NULL,
    VL_RECEITA DECIMAL(10, 2) NOT NULL,
    DT_RECEITA DATETIME NOT NULL,
    TX_DESCRICAO VARCHAR(200),
    FOREIGN KEY (ID_RECEITA) REFERENCES TBL_RECEITA(ID_RECEITA)
);
